# Indian Weather & Rainfall Analysis
## 01 - Data Loading

### Objective
#### The objective of this notebook is to load the Indian Weather & Rainfall dataset, understand its structure, inspect the available features, and perform an initial exploration before data cleaning and analysis.

## Import Required Library

In [1]:
import pandas as pd

## Load Dataset

In [2]:
df = pd.read_csv("../data/india_weather_rainfall_data.csv")
df.head()

,date_of_record,month,season,station_name,state,district,avg_temp,min_temp,max_temp,wind_speed,air_pressure,elevation,latitude,longitude,rainfall
0,2021-01-02 00:00:00,January,Winter,Gulmarg,JK,Baramulla,-2.2,-6.6,-0.8,2.2,1020.0,2652,34.05,74.4,0.1
1,2021-01-03 00:00:00,January,Winter,Gulmarg,JK,Baramulla,-3.6,-4.6,-1.8,3.7,1019.5,2652,34.05,74.4,4.4
2,2021-01-04 00:00:00,January,Winter,Gulmarg,JK,Baramulla,-3.0,-4.5,-1.1,2.1,1022.0,2652,34.05,74.4,2.3
3,2021-01-05 00:00:00,January,Winter,Gulmarg,JK,Baramulla,-3.3,-5.1,-1.2,2.8,1015.6,2652,34.05,74.4,35.0
4,2021-01-06 00:00:00,January,Winter,Gulmarg,JK,Baramulla,-3.9,-8.3,-1.0,3.4,1015.3,2652,34.05,74.4,25.5

In [3]:
df.shape

(970339, 15)

In [4]:
df.tail()

,date_of_record,month,season,station_name,state,district,avg_temp,min_temp,max_temp,wind_speed,air_pressure,elevation,latitude,longitude,rainfall
970334,2025-02-06 00:00:00,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,27.3,22.0,34.0,7.6,1011.4,5,17.7167,83.2333,0.0
970335,2025-02-07 00:00:00,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.7,23.0,30.0,7.7,1013.1,5,17.7167,83.2333,0.3
970336,2025-02-08 00:00:00,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.5,23.0,30.0,8.7,1013.0,5,17.7167,83.2333,0.0
970337,2025-02-09 00:00:00,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,26.5,23.0,30.0,8.5,1012.8,5,17.7167,83.2333,0.0
970338,2025-02-10 00:00:00,February,Winter,Vizagapatam / Gajuwaka,AP,Visakhapatnam,25.5,21.8,31.0,8.2,1013.9,5,17.7167,83.2333,0.0

## Dataset Columns

In [5]:
df.columns

Index(['date_of_record', 'month', 'season', 'station_name', 'state',
       'district', 'avg_temp', 'min_temp', 'max_temp', 'wind_speed',
       'air_pressure', 'elevation', 'latitude', 'longitude', 'rainfall'],
      dtype='str')

## Dataset Information

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 970339 entries, 0 to 970338
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   date_of_record  970339 non-null  str
 1   month           970339 non-null  str
 2   season          970339 non-null  str
 3   station_name    970339 non-null  str
 4   state           970339 non-null  str
 5   district        970339 non-null  str
 6   avg_temp        970339 non-null  float64
 7   min_temp        926441 non-null  float64
 8   max_temp        859741 non-null  float64
 9   wind_speed      695895 non-null  float64
 10  air_pressure    665675 non-null  float64
 11  elevation       970339 non-null  int64
 12  latitude        970339 non-null  float64
 13  longitude       970339 non-null  float64
 14  rainfall        712785 non-null  float64
dtypes: float64(8), int64(1), str(6)
memory usage: 161.2 MB

## Missing Values

In [7]:
df.isnull().sum()

date_of_record         0
month                  0
season                 0
station_name           0
state                  0
district               0
avg_temp               0
min_temp           43898
max_temp          110598
wind_speed        274444
air_pressure      304664
elevation              0
latitude               0
longitude              0
rainfall          257554
dtype: int64

## Statistical Summary

In [8]:
df.describe()

,avg_temp,min_temp,max_temp,wind_speed,air_pressure,elevation,latitude,longitude,rainfall
count,970339.000000,926441.000000,859741.000000,695895.000000,665675.000000,970339.000000,970339.000000,970339.000000,712785.000000
mean,25.661709,20.647342,31.195383,9.432732,1009.437663,298.181018,20.793670,79.426826,5.267533
std,5.438133,6.008171,5.464499,4.979263,5.292871,415.266215,6.328275,5.852512,14.444142
min,-10.400000,-18.500000,-5.600000,0.000000,922.600000,0.000000,7.983300,68.850000,0.000000
25%,23.100000,17.100000,28.500000,6.100000,1005.800000,16.000000,15.850000,75.400000,0.000000
50%,26.700000,22.400000,31.600000,8.400000,1009.800000,139.000000,21.616700,78.066700,0.000000
75%,29.100000,25.000000,34.400000,11.600000,1013.300000,436.000000,25.566700,82.716700,4.000000
max,43.400000,36.600000,87.000000,66.600000,1036.500000,2652.000000,34.083300,95.383300,485.900000

## Duplicate Records

In [9]:
df.duplicated().sum()

np.int64(0)

## Next Step

### In the next notebook, we will:

#### - Handle missing values
#### - Remove duplicate records
#### - Fix incorrect data types (if required)
#### - Detect and treat outliers
#### - Prepare the dataset for Exploratory Data Analysis (EDA)